import Head from 'next/head';
import { customServerSideTranslations, requireAuthUser } from '../../../apps/api/functions';
import { UserStoryGenerator } from '../../../apps/front/components';
import { wrapper } from '../../../store';

export default function NewStoryPage() {
    return (
        <>
            <Head>
                <title>Nouvelle histoire - My StoryBook </title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link
                    rel='icon'
                    href='/favicon.ico'
                />
            </Head>
            <UserStoryGenerator />
        </>
    );
}

export const getServerSideProps = wrapper.getServerSideProps((store) => async (context) => {
    return requireAuthUser(store, context, async () => ({
        props: {
            ...(await customServerSideTranslations(context.locale!, ['story-generator', 'story-inputs'])),
        },
    }));
});
